### ISSUE TITLE
Allow faking custom types

### ISSUE THREAD

**Issue by yakir12** [neomatrixcode/Faker.jl#20]
Users generate custom types that they need to fake.

Exposing a method or two that the user needs to define for her custom type may allow her to fake instances of that type.

Right now it she needs to construct the instance from a combination of the types you already defined.

This is useful when seeding a database for testing/developing.

**Comment by yakir12** [comment]
I'm inclined to close this. Here is what I needed to do to define a fake custom user for my specific needs:
```
fakeuser(id) = User(
                  DbId(id),
                  string(Faker.first_name(), " ", Faker.last_name()),
                  Faker.user_name(),
                  Faker.password(),
                  Faker.email())
```
I can not see how this can be made simpler than it already is. 

I'll leave this to your discretion.

**Comment by neomatrixcode** [comment]
Currently there is the `profile` method:

https://github.com/neomatrixcode/Faker.jl/blob/3e684b6e9696d3ec0973b5ee5f81eafdefdde47a/src/persona.jl#L37

internally has a dictionary. However, the method he proposes is more flexible. The function will be added in the next version. 

Thank you very much for your contribution.

**Comment by neomatrixcode** [comment]
Thanks for your contribution, this feature has been added to version 0.3 of Faker, here you will find links with more information.

https://app.gitbook.com/@neomatrixcode/s/faker/guide/providers/person

https://app.gitbook.com/@neomatrixcode/s/faker/guide/generator

**Comment by yakir12** [comment]
Wow, looks great!
