### ISSUE TITLE
unicode?

### ISSUE THREAD

**Issue by yakir12** [neomatrixcode/Faker.jl#6]
How about a generator that includes "all" unicode, symbols, punctuations, tabs, line-breaks, slashes, the works?

**Comment by codeneomatrix** [comment]
Yes, it is a good idea. I will take it into account for the next versions of Faker.
Thank you

**Comment by neomatrixcode** [comment]
Thanks for your contribution, this feature has been added to version 0.3 of Faker, here you will find links with more information.

https://neomatrixcode.gitbook.io/faker/guide/providers/base

**Comment by yakir12** [comment]
Awesome!
